add file index.html and style.html
gsg-K1-FC/team2-real-story pull request #5
Opened 2020-10-11 19:03 UTC by anaal

- add file index.html style.css 
- add section bio
- add div container
- add class
- add image
- add  two paragraphs
- add  css formats

2020-10-12 10:28 UTC, YakoobHammouri requested changes

2020-10-12 10:28 UTC, YakoobHammouri commented on index.html
> +                        <img src="https://static.wixstatic.com/media/84770f_af85ac0d80ee4234a56e871016b9e661~mv2_d_5000_3625_s_4_2.jpg/v1/fill/w_389,h_282,al_c,q_80,usm_0.66_1.00_0.01/84770f_af85ac0d
download the image in your project, to use as a local asset

2020-10-12 10:28 UTC, YakoobHammouri commented on index.html
> +            <span class="bio" ><p>BIO</p></span>
why put the p tag inside the span tag?

2020-10-12 10:28 UTC, YakoobHammouri commented on style.css
> +img{
recommend using class Name not a tag type, 
by using the img tag all image in the site will take this CSS

2020-10-12 10:28 UTC, YakoobHammouri commented on style.css
> +.section2{
the name must be descriptive

2020-10-12 10:28 UTC, YakoobHammouri commented on style.css
> +    width:900px;
why using fixed width?

2020-10-12 10:28 UTC, YakoobHammouri commented on style.css
> +.str{
the name must be descriptive

2020-10-12 10:28 UTC, YakoobHammouri commented on style.css
> +.par1{
what is the name convention using her?

2020-10-12 10:28 UTC, YakoobHammouri commented on style.css
> +.par2{
what is the name convention using her?

2020-10-12 14:22 UTC, YakoobHammouri requested changes

2020-10-12 14:22 UTC, YakoobHammouri commented on style.css
> +    float: left;
do not use float, use flex

2020-10-12 14:22 UTC, YakoobHammouri commented on style.css
> +    float: left;
do not use float, use flex

2020-10-12 14:22 UTC, YakoobHammouri commented on style.css
> +    height: 300px;
do not use fix width

2020-10-12 14:22 UTC, YakoobHammouri commented on style.css
> +.content{
change  to flex

2020-10-12 14:22 UTC, YakoobHammouri commented on style.css
> +    height: 300px;
do not use fix width

2020-10-13 09:53 UTC, YakoobHammouri approved these changes

2020-10-13 10:18 UTC, sarah-alsharif0 requested changes

2020-10-13 10:18 UTC, sarah-alsharif0 commented on index.html
> +                    <div class="bio-box ">
I recommend using the BEM convention in naming the classes like : 
`bio__header` , `bio__box`
like what the mentor @YakoobHammouri has said.

2020-10-13 12:24 UTC, MontaserSaleh91 approved these changes

2020-10-13 18:09 UTC, merged